# Generated by Django 3.0.5 on 2020-04-08 19:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import guard_engine.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecuredUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_route', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=96)),
                ('creation_date', models.DateField()),
                ('expire_ts', models.DateTimeField()),
                ('visit_counter', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('latest_user_agent', models.CharField(blank=True, max_length=64)),
                ('url_route', models.URLField(max_length=2048)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SecuredFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_route', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=96)),
                ('creation_date', models.DateField()),
                ('expire_ts', models.DateTimeField()),
                ('visit_counter', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('latest_user_agent', models.CharField(blank=True, max_length=64)),
                ('file_size', models.PositiveIntegerField()),
                ('persisted_file', models.FileField(upload_to=guard_engine.models.upload_to)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
